package Entidades;
// Generated 09-12-2019 05:40:04 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transacciones generated by hbm2java
 */
@Entity
@Table(name="transacciones"
    ,schema="public"
)
public class Transacciones  implements java.io.Serializable {


     private long codigo;
     private Cuentas cuentas;
     private Date fecha;
     private int npartida;
     private String descripcion;
     private BigDecimal cargo;
     private BigDecimal abono;

    public Transacciones() {
    }

	
    public Transacciones(long codigo, Cuentas cuentas, Date fecha, int npartida) {
        this.codigo = codigo;
        this.cuentas = cuentas;
        this.fecha = fecha;
        this.npartida = npartida;
    }
    public Transacciones(long codigo, Cuentas cuentas, Date fecha, int npartida, String descripcion, BigDecimal cargo, BigDecimal abono) {
       this.codigo = codigo;
       this.cuentas = cuentas;
       this.fecha = fecha;
       this.npartida = npartida;
       this.descripcion = descripcion;
       this.cargo = cargo;
       this.abono = abono;
    }
   
     @Id 

    
    @Column(name="codigo", unique=true, nullable=false)
    public long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(long codigo) {
        this.codigo = codigo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cuenta", nullable=false)
    public Cuentas getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Cuentas cuentas) {
        this.cuentas = cuentas;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="npartida", nullable=false)
    public int getNpartida() {
        return this.npartida;
    }
    
    public void setNpartida(int npartida) {
        this.npartida = npartida;
    }

    
    @Column(name="descripcion", length=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="cargo", precision=16)
    public BigDecimal getCargo() {
        return this.cargo;
    }
    
    public void setCargo(BigDecimal cargo) {
        this.cargo = cargo;
    }

    
    @Column(name="abono", precision=16)
    public BigDecimal getAbono() {
        return this.abono;
    }
    
    public void setAbono(BigDecimal abono) {
        this.abono = abono;
    }




}


